version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        links:
            - db
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: top-pack
            MYSQL_USER: top-pack
            MYSQL_ROOT_PASSWORD: top-pack
        ports:
            - 3306:3306
