version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:top-pack
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            MYSQL_DATABASE: top-pack
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: top-pack
        links:
            - db
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_HOST: 0.0.0.0
            MYSQL_DATABASE: top-pack
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: top-pack
        ports:
            - 3306:3306
